---
title: "Lab 10 11-5-21"
output: 
  html_document: default
  github_document:
    html_preview: true
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
```

```{r}
# install.packages(c("RSQLite", "DBI"))

library(RSQLite)
library(DBI)

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
```

Are the tables there? 
```{r}
dbListTables(con)
```

You can also use knitr + SQL (used SQL to store output as X1), or use 'dbGetquery'
```{sql, connection=con, output.var="x1"} 
PRAGMA table_info(actor)
```

```{r}
x1
```

```{r}
dbGetQuery(con, "PRAGMA table_info(actor)")
```
Exercise 1
```{r}
dbGetQuery(con, "
  SELECT actor_id, first_name, last_name
  FROM actor
  ORDER by last_name, first_name
  LIMIT 5")
```
```{r}
dbGetQuery(con, "
  SELECT actor_id, first_name, last_name
  FROM actor
  WHERE last_name IN ('WILLIAMS', 'DAVIS')
  LIMIT 5")
```
```{r}
dbGetQuery(con, "
  SELECT DISTINCT customer_id
  FROM rental
  WHERE date(rental_date) = '2005-07-05' LIMIT 5")
```

Exercise 4
```{r}
dbGetQuery(con, "PRAGMA table_info(payment)")
```
4.1
```{r}
q <- dbSendQuery(con, "
SELECT *
FROM payment
WHERE amount IN (1.99, 7.99, 9.99)"
)
dbFetch(q, n = 10)
```
```{r}
dbFetch(q, n = 10)
```
4.2 
```{r}
dbGetQuery(con, "
SELECT *
FROM payment
WHERE amount > 5 LIMIT 5")
```
Bonus: Count how many there are
```{r}
dbGetQuery(con, "
SELECT COUNT(*)
FROM payment
WHERE amount > 5")
```
Counting per 'staff_id'
```{r}
dbGetQuery(con, "
SELECT staff_id, COUNT(*) AS N
FROM payment
/* GROUP BY goes AFTER WHERE*/
WHERE amount > 5
GROUP BY staff_id
")
```
Exercise 5:
```{r}
dbGetQuery(con, "
SELECT p.payment_id, p.amount
FROM payment AS p
INNER JOIN customer AS c ON p.customer_id=c.customer_id
WHERE c.last_name = 'DAVIS'")
```
Exercise 6:
```{r}
dbGetQuery(con, "
SELECT COUNT(*)
FROM rental")
```
6.2
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS 'N_rentals'
FROM rental
GROUP BY customer_id LIMIT 5")
```
#6.3
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS 'N_rentals'
FROM rental
GROUP BY customer_id
ORDER BY N_rentals DESC
LIMIT 5")
```
6.4
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS 'N_rentals'
FROM rental
GROUP BY customer_id
HAVING COUNT (*) >= 40
ORDER BY N_rentals DESC")
```
Exercise 7
```{r}
dbGetQuery(con, "
  SELECT customer_id, 
  AVG(amount) AS 'avg', 
  MAX(amount) AS 'max', 
  MIN(amount) AS 'min',
  SUM(amount) AS 'sum'
  FROM payment GROUP BY customer_id LIMIT 5")
```
7.2
```{r}
dbGetQuery(con, "
  SELECT customer_id, 
  AVG(amount) AS 'avg', 
  MAX(amount) AS 'max', 
  MIN(amount) AS 'min',
  SUM(amount) AS 'sum'
  FROM payment 
  GROUP BY customer_id
  HAVING COUNT (*) >5")
```
Clean Up
```{r}
dbDisconnect(con)
```

