---
title: "PM 566- Lab 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Step 1- Read the Data 

```{r}

#install if only not installed
if (!require(data.table)) {
  install.packages("data.table")
}

#only download if we don't have the file
if(!file.exists("met_all.gz")) {
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", method="libcurl", 
              timeout = 60)
}
met <- data.table::fread("met_all.gz")
```

2. Check the dimensions, headers, footers. How many columns, rows are there?

```{r}
dim(met)
head(met)
tail(met)

```

Step 3- Take a look at the variables 

```{r}
str(met)
```

Step 4- Take a closer look at the key variables 

```{r}
table(met$year)
```

```{r}
table(met$day)
```

```{r}
table(met$hour)
```

```{r}
summary(met$temp)
```

```{r}
summary(met$elev)
```

```{r}
summary(met$wind.sp)
```

Updating NAs in elevation 

```{r}
#met[met$elev==9999.0] <- NA
met[elev == 9999.0, elev := NA]
summary(met$elev)
```

The highest weather station is at `r max(met$elev, na.rm = TRUE)` ft. Now we need to fix the temperature.


```{r}
#met <- met[temp>-15]
#met2 <- met[order(temp)]
#head(met2)

met <- met[temp>-15][order(temp)]
summary(met[, .(lat, lon, wind.sp, temp, elev)])
```

6. Calculate summary statistics 

```{r}
met[elev==max(elev, na.rm = TRUE)][, summary(wind.sp)]
met[elev==max(elev, na.rm = TRUE)][, summary(temp)]
```

```{r}
met[elev==max(elev, na.rm = TRUE)] , .(
  temp_wind= cor(temp, wind.sp, use= "complete")
  temp_hour= cor(temp, hour, use= "complete")
  temp_day= cor(temp, day, use= "complete")
  wind_day= cor(wind.sp, day, use = "complete")
  wind_hour= cor(wind.sp, hour, use= "complete")
)]
```

Step 7: Exploratory Graphs

```{r}
hist(met$elev, breaks = 100)
```

